Changes: - `command-has`: Now checks for functions as well. - `load_zfunc`: Corrected zsh expansion when looking for function files. - `load_zfunc`: Unsetting only loaded functions; this prevents error messages about unsetting "undefined functions". - `zsource`: Added - Updated TODO.

diff --git a/custom/functions/base/command-has b/custom/functions/base/command-has
--- a/custom/functions/base/command-has
+++ b/custom/functions/base/command-has
@@ -1,4 +1,4 @@
-# Checks argument list for installed commands.
+# Checks argument list for valid commands.
 # Can make use of operators AND and OR.
 
 emulate -L zsh
@@ -7,8 +7,8 @@ local -r usage=(
 	"Usage: $(get_funcname) [OPTION...] COMMAND..."
 	"\t[-h|--help] : Print this help message"
 	"\t[-v] / [-q] : Increase / Decrease verbosity"
-	"\t[-o|--or] : Logical OR operator. Default behavior. Checks if any of the commands are installed."
-	"\t[-a|--and] : Logical AND operator. Checks if all of the commands are installed."
+	"\t[-o|--or] : Logical OR operator. Default behavior. Checks if any of the commands are valid."
+	"\t[-a|--and] : Logical AND operator. Checks if all of the commands are valid."
 )
 
 ## Setup func opts
@@ -33,13 +33,13 @@ local verbosity=0
 logical=${logical##*-}
 
 ## function logic
-local -aU installed=(${(k)commands[(I)${(j:|:)@}]})
-local -aU non_installed=(${@:|installed})
+local -aU valid=(${(k)commands[(I)${(j:|:)@}]} ${(k)functions[(I)${(j:|:)@}]})
+local -aU invalid=(${@:|valid})
 
-## Print non-installed commands
-if (( $verbosity )) && (( ${#non_installed} )); then
-	>&2 echo "Non-installed commands:"
-	>&2 echo "${non_installed}"
+## Print non-valid commands
+if (( $verbosity )) && (( ${#invalid} )); then
+	>&2 echo "Invalid commands:"
+	>&2 echo "${invalid}"
 fi
-{ (( ! ${#non_installed} )) && [[ "$logical" =~ a(nd)? ]] } ||
-{ (( ${#installed} )) && [[ "$logical" =~ o(r)? ]] }
+{ (( ! ${#invalid} )) && [[ "$logical" =~ a(nd)? ]] } ||
+{ (( ${#valid} )) && [[ "$logical" =~ o(r)? ]] }
