Fixed `command-has` command filter/search

diff --git a/custom/functions/base/command-has b/custom/functions/base/command-has
--- a/custom/functions/base/command-has
+++ b/custom/functions/base/command-has
@@ -45,10 +45,11 @@ if (( $verbosity )); then
 	local -aU invalid=(${@:|valid})
 	if (( ${#invalid} )); then
 		print_fn -e "Not found:"
-		>&2 echo "${(j:, :)invalid}"
+		>&2 printf '%s\n' "${(j:, :)invalid}"
 	fi
 fi
 
 # Fastest process to check for commands
-{ [[ -z "${logical#a(nd)?#}" ]] && command -v ${@} &>/dev/null } ||
-{ [[ -z "${logical#o(r)?#}" ]] && (( ${(v)#commands[(I)($args)]} + ${#functions[(I)($args)]} + ${#aliases[(I)($args)]} )) }
+local results=$((${(v)#commands[(I)($args)]} + ${#functions[(I)($args)]} + ${#aliases[(I)($args)]}))
+{ [[ "${logical}" == (a|and) ]] && (( $# == $results )) } ||
+{ [[ "${logical}" == (o|or) ]] && (( $results )) }
